name: Run Tests
on:
    push:
      branches:
        - 'master'
    pull_request:
      types: [opened, synchronize, reopened]
    release:
        types:
          - created
jobs:
    test_and_package:
        runs-on: ubuntu-latest
        continue-on-error: false
        steps:
            - name: Checking out code base
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11
            - name: Cache SonarCloud packages
              uses: actions/cache@v1
              with:
                path: ~/.sonar/cache
                key: ${{ runner.os }}-sonar
                restore-keys: ${{ runner.os }}-sonar
            - name: Cache Maven packages
              uses: actions/cache@v1
              with:
                path: ~/.m2
                key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                restore-keys: ${{ runner.os }}-m2
            - name: Testing and Packaging
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: mvn -B verify -Psonar -Dmaven.test.failure.ignore=false
              continue-on-error: false
